import type { Project } from "@/types/database";

export const mockGalleries: Project[] = [
  {
    id: "gal_1",
    owner_id: "user_demo",
    title: "Alicia & James — Wedding",
    client_name: "Alicia Chen",
    description: "Full-day wedding coverage, Grand Hyatt",
    status: "proofing",
    selection_limit: 40,
    created_at: "2026-07-10T10:00:00Z",
    updated_at: "2026-07-18T14:30:00Z",
    photo_count: 286,
    selection_count: 32,
  },
  {
    id: "gal_2",
    owner_id: "user_demo",
    title: "Sarah Pre-wedding",
    client_name: "Sarah Wong",
    description: "Golden hour session at Discovery Bay",
    status: "shared",
    selection_limit: 25,
    created_at: "2026-07-14T09:00:00Z",
    updated_at: "2026-07-16T11:00:00Z",
    photo_count: 94,
    selection_count: 0,
  },
  {
    id: "gal_3",
    owner_id: "user_demo",
    title: "Lin Family Portrait",
    client_name: "David Lin",
    description: "Studio + outdoor combo session",
    status: "draft",
    selection_limit: 20,
    created_at: "2026-07-20T08:00:00Z",
    updated_at: "2026-07-20T08:00:00Z",
    photo_count: 48,
    selection_count: 0,
  },
  {
    id: "gal_4",
    owner_id: "user_demo",
    title: "Mei & Kai — Final Delivery",
    client_name: "Mei Tan",
    description: "Retouched finals ready for download",
    status: "final",
    selection_limit: 30,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-07-05T16:00:00Z",
    photo_count: 30,
    selection_count: 30,
  },
];
